package dev.herrerao;

import java.io.File;
import java.sql.*;
import java.util.ArrayList;
import java.util.HashMap;

/*
    For the DataStorage class, I am using HSQLDB as the underlying database.
    The DataStorage class creates a new connection per operation and closes it.
    HSQLDB handles thread safety internally at the database level, by managing concurrent access
    across those connections using its own internal locking and transaction system. Therefore,
    no synchronized blocks are needed in the DataStorage class.
 */

public class DataStorage {
    private String DB_PATH = "./data/mydb";
    private String url = "jdbc:hsqldb:file:" + DB_PATH + ";shutdown=true";
    private String username = "sa";
    private String password = "as";

    /*
        When a new instance is created, a check is made to determine if the database exists in the filesystem.
        If it doesn't, the database is created.
     */
    public DataStorage() throws Exception {
        Class.forName("org.hsqldb.jdbc.JDBCDriver");
        if (!checkIfDatabaseExists()) {
            System.out.println("Setting up database...");
            Connection conn = DriverManager.getConnection(this.url, this.username, this.password);
            initializeDatabase(conn);
        } else {
            System.out.println("Database already exists.");
        }
    }

    /*
        Checks if database on disk.
     */
    private boolean checkIfDatabaseExists() {
        return new File(DB_PATH + ".properties").exists();
    }

    /*
        Creates the tables for users and messages.
     */
    private void initializeDatabase(Connection conn) throws Exception {
        // create table
        try(Statement stmt = conn.createStatement()) {
            stmt.executeUpdate("""
           CREATE TABLE users (
               id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
               name VARCHAR(100) NOT NULL,
               password VARCHAR(100) NOT NULL
           )
           """);

            stmt.executeUpdate("""
            CREATE TABLE messages (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sender_id INTEGER NOT NULL,
                recipient_id INTEGER NOT NULL,
                subject VARCHAR(200),
                body VARCHAR(4000) NOT NULL,
                sent_at TIMESTAMP DEFAULT NOW(),
                is_read BOOLEAN DEFAULT FALSE,
                FOREIGN KEY(sender_id) REFERENCES users(id),
                FOREIGN KEY(recipient_id) REFERENCES users(id)
                )
                """);
        } finally {
            conn.close();
        }
    }

    /*
        Insert a user into the database.
     */
    public Boolean addUser(String username, String password) throws Exception {
       int status = 0;
       try (Connection conn = DriverManager.getConnection(this.url, this.username, this.password);
            PreparedStatement stmt = conn.prepareStatement(
               "INSERT INTO users (name, password) VALUES (?, ?)")) {
           stmt.setString(1, username);
           stmt.setString(2, password);
           status = stmt.executeUpdate();

       }
       return (status > 0);
    }

    /*
        Inserts a message into the database using a message record.
     */
    public Boolean insertMessage(Message message) throws Exception {
        return insertMessage(message.senderID(), message.recipientID(), message.subject(), message.body());
    }

    public Boolean insertMessage(int sender_id, int recipient_id, String subject, String body) throws Exception {
        int status = 0;
        try (Connection conn = DriverManager.getConnection(this.url, this.username, this.password);
            PreparedStatement stmt = conn.prepareStatement(
                    "INSERT INTO messages (sender_id, recipient_id, subject, body) VALUES (?, ?, ?, ?)"
            )) {
            stmt.setInt(1, sender_id);
            stmt.setInt(2, recipient_id);
            stmt.setString(3, subject);
            stmt.setString(4, body);
            status = stmt.executeUpdate();
        }
        return (status > 0);
    }

    /*
        Queries the database for a user's ID
     */
    public int getUserID(String username) throws Exception {
        int userID = -1;
        String sql = "SELECT id FROM users WHERE name = ?";

        try (Connection conn = DriverManager.getConnection(this.url, this.username, this.password);
            PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, username);

            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                userID = rs.getInt("id");
            }
        }

        return userID;
    }

    /*
        Queries a specific user from the database and returns a User record.
     */
    public User getUser(String username, String password) throws Exception {
        User user = null;
        String sql = "SELECT id, name FROM users WHERE name = ? AND password = ?";
        try (Connection conn = DriverManager.getConnection(this.url, this.username, this.password);
        PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, username);
            stmt.setString(2, password);

            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                user = new User(rs.getInt("id"), rs.getString("name"));
            }
        };

        return user;
    }

    /*
        Queries database for set of messages by recipientID.
        Method returns a HashMap<Integer, ArrayList<message>> object to client.
     */
    public HashMap<Integer, ArrayList<Message>> getMessages(int recipientID) throws Exception {
        HashMap<Integer, ArrayList<Message>> cache = new HashMap<>();
        String sql = """
            SELECT m.id, m.sender_id, m.recipient_id, u.name AS sender_name, m.subject, m.body, m.sent_at, m.is_read
            FROM messages m
            JOIN users u ON m.sender_id = u.id
            WHERE m.recipient_id = ?;
            """;
        try (Connection conn = DriverManager.getConnection(this.url, this.username, this.password);
            PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.setInt(1, recipientID);
                ResultSet rs = stmt.executeQuery();

                while (rs.next()) {
                    Message query = new Message(
                            rs.getInt("id"),
                            rs.getInt("sender_id"),
                            rs.getInt("recipient_id"),
                            rs.getString("sender_name"),
                            rs.getString("subject"),
                            rs.getString("body"),
                            rs.getTimestamp("sent_at").toLocalDateTime(),
                            rs.getBoolean("is_read")
                    );

                    if (cache.containsKey(query.senderID())) {
                        ArrayList<Message> list = cache.get(query.senderID());
                        list.add(query);
                    } else {
                        ArrayList<Message> list = new ArrayList<>();
                        list.add(query);
                        cache.put(query.senderID(), list);
                    }
                }
        }
        return cache;
    }

}
