package dev.herrerao;

import java.io.File;
import java.io.IOException;
import java.sql.*;
import java.util.ArrayList;
import java.util.HashMap;

public class DataStorage {
    private String DB_PATH = "./data/mydb";
    private String url = "jdbc:hsqldb:file:" + DB_PATH + ";shutdown=true";
    private String username = "sa";
    private String password = "as";

    public DataStorage() throws Exception {
        Class.forName("org.hsqldb.jdbc.JDBCDriver");
        if (!checkIfDatabaseExists()) {
            System.out.println("Setting up database...");
            Connection conn = DriverManager.getConnection(this.url, this.username, this.password);
            initializeDatabase(conn);
        } else {
            System.out.println("Database already exists.");
        }
    }

    private boolean checkIfDatabaseExists() {
        return new File(DB_PATH + ".properties").exists();
    }

    private void initializeDatabase(Connection conn) throws Exception {
        // create table
        try(Statement stmt = conn.createStatement()) {
            stmt.executeUpdate("""
           CREATE TABLE users (
               id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
               name VARCHAR(100) NOT NULL,
               password VARCHAR(100) NOT NULL
           )
           """);

            stmt.executeUpdate("""
            CREATE TABLE messages (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sender_id INTEGER NOT NULL,
                recipient_id INTEGER NOT NULL,
                subject VARCHAR(200),
                body VARCHAR(4000) NOT NULL,
                sent_at TIMESTAMP DEFAULT NOW(),
                is_read BOOLEAN DEFAULT FALSE,
                FOREIGN KEY(sender_id) REFERENCES users(id),
                FOREIGN KEY(recipient_id) REFERENCES users(id)
                )
                """);
        } finally {
            conn.close();
        }
    }

    public Boolean addUser(String username, String password) throws Exception {
       int status = 0;
       try (Connection conn = DriverManager.getConnection(this.url, this.username, this.password);
            PreparedStatement stmt = conn.prepareStatement(
               "INSERT INTO users (name, password) VALUES (?, ?)")) {
           stmt.setString(1, username);
           stmt.setString(2, password);
           status = stmt.executeUpdate();

       }
       return (status > 0);
    }

    public Boolean sendMessage(String sender_id, String recipient_id, String subject, String body) throws Exception {
        int status = 0;
        try (Connection conn = DriverManager.getConnection(this.url, this.username, this.password);
            PreparedStatement stmt = conn.prepareStatement(
                    "INSERT INTO messages (sender_id, recipient_id, subject, body) VALUES (?, ?, ?, ?)"
            )) {
            stmt.setString(1, sender_id);
            stmt.setString(2, recipient_id);
            stmt.setString(3, subject);
            stmt.setString(4, body);
            status = stmt.executeUpdate();
        }
        return (status > 0);
    }

    public int getUserID(String username) throws Exception {
        int userID = -1;
        String sql = "SELECT id FROM users WHERE name = ?";

        try (Connection conn = DriverManager.getConnection(this.url, this.username, this.password);
            PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, username);

            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                userID = rs.getInt("id");
            }
        }

        return userID;
    }

    public HashMap<Integer, ArrayList<Message>> getMessages(int recipientID) throws Exception {
        HashMap<Integer, ArrayList<Message>> cache = new HashMap<>();
        String sql = """
            SELECT m.id, m.sender_id, u.name AS sender_name, m.subject, m.body, m.sent_at, m.is_read
            FROM messages m
            JOIN users u ON m.sender_id = u.id
            WHERE m.recipient_id = ?;
            """;
        try (Connection conn = DriverManager.getConnection(this.url, this.username, this.password);
            PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.setInt(1, recipientID);
                ResultSet rs = stmt.executeQuery();

                while (rs.next()) {
                    Message query = new Message(
                            rs.getInt("id"),
                            rs.getInt("sender_id"),
                            rs.getString("sender_name"),
                            rs.getString("subject"),
                            rs.getString("body"),
                            rs.getTimestamp("sent_at").toLocalDateTime(),
                            rs.getBoolean("is_read")
                    );

                    if (cache.containsKey(query.senderID())) {
                        ArrayList<Message> list = cache.get(query.senderID());
                        list.add(query);
                    } else {
                        ArrayList<Message> list = new ArrayList<>();
                        list.add(query);
                        cache.put(query.senderID(), list);
                    }
                }
        }
        return cache;
    }

}
