package dev.herrerao;

import java.io.File;
import java.io.IOException;
import java.sql.*;

public class DataStorage {
    private String DB_PATH = "./data/mydb";
    private String url = "jdbc:hsqldb:file:" + DB_PATH + ";shutdown=true";
    private String username = "sa";
    private String password = "";

    public DataStorage() {}

    private boolean checkIfDatabaseExists() {
        return new File(DB_PATH + ".properties").exists();
    }

    private void initializeDatabase(Connection conn) throws Exception {
        // create table
        try(Statement stmt = conn.createStatement()) {
            stmt.executeUpdate("""
           CREATE TABLE users (
               id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
               name VARCHAR(100) NOT NULL,
               password VARCHAR(100) NOT NULL
           )
           """);

            stmt.executeUpdate("""
            CREATE TABLE messages (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sender_id INTEGER NOT NULL,
                recipient_id INTEGER NOT NULL,
                subject VARCHAR(200),
                body VARCHAR(4000) NOT NULL,
                sent_at TIMESTAMP DEFAULT NOW(),
                is_read BOOLEAN DEFAULT FALSE,
                FOREIGN KEY(sender_id) REFERENCES users(id),
                FOREIGN KEY(recipient_id) REFERENCES users(id),
                )
                """);
        }
    }

    public Boolean addUser(String username, String password) throws Exception {
       int status = 0;
       try (Connection conn = DriverManager.getConnection(this.url, this.username, this.password);
            PreparedStatement stmt = conn.prepareStatement(
               "INSERT INTO users (name, password) VALUES (?, ?)")) {
           stmt.setString(1, username);
           stmt.setString(2, password);
           status = stmt.executeUpdate();

       }
       return (status > 0);
    }

    public int getUserID(String username) throws Exception {
        int userID = 0;
        String sql = "SELECT id FROM users WHERE username = ?";

        try (Connection conn = DriverManager.getConnection(this.url, this.username, this.password);
            PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, username);

            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                userID = rs.getInt("id");
            }
        }

        return userID;
    }

}
